name: Publish package to GitHub Packages
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'packages/logger'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ahmed_test'
      - name: Install dependencies
        run: npm ci
        working-directory: packages/logger
      - name: Build
        run: npm run build
        working-directory: packages/logger
      - name: Push the package
        run: npm publish
        working-directory: packages/logger
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
