name: Trigger repos

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: false

jobs:
  trigger:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['service-ui', 'service-api', 'service-auth']
    steps:
      - name: Trigger workflows
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ahmedazhazh
          repo: ${{ matrix.repo }}
          github_token: ${{ secrets.PAT }}
          workflow_file_name: create-ec2.yml
          ref: develop
          wait_interval: 60
          client_payload: '{}'
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true
