name: Release job
on: workflow_dispatch
jobs:

  do-the-job:
    name: Docker run
    runs-on: rp-release
    steps:
      - name: Run Docker compose up
        run: docker compose -p reportportal up -d
