name: Release job
on: workflow_dispatch

jobs:
  ec2-start:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Start EC2 instances
        uses: aws-actions/ec2-manage-instances@v1
        with:
          action: start
          instance-ids: i-05d13ef5ca7ba3de1

  do-the-job:
    name: Docker run
    runs-on: rp-release
    needs: ec2-start
    steps:
      - name: Run Docker compose up
        run: docker compose -p reportportal up -d

  ec2-stop:
    runs-on: ubuntu-latest
    needs: do-the-job
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Stop EC2 instances
        uses: aws-actions/ec2-manage-instances@v1
        with:
          action: stop
          instance-ids: i-05d13ef5ca7ba3de1
